<template><div class="app-container">
  <vxe-form :data="query" @submit="search" @reset="reset">
    <vxe-form-item title="申报单号"><template #default><vxe-input v-model="query.declarationNo" clearable/></template></vxe-form-item>
    <vxe-form-item title="客户"><template #default><vxe-input v-model="query.customerName" clearable/></template></vxe-form-item>
    <vxe-form-item title="状态"><template #default><vxe-select v-model="query.status" clearable><vxe-option value="PENDING" label="待审核"/><vxe-option value="CONFIRMED" label="已通过"/><vxe-option value="REJECTED" label="已驳回"/></vxe-select></template></vxe-form-item>
    <vxe-form-item><template #default><vxe-button type="submit" status="primary">查询</vxe-button><vxe-button type="reset">重置</vxe-button></template></vxe-form-item>
  </vxe-form>
  <vxe-table border stripe :loading="loading" :data="rows">
    <vxe-column field="declarationNo" title="申报单号" width="180"/><vxe-column field="customerName" title="客户" min-width="140"/><vxe-column field="shipmentNo" title="出货计划" width="180"/>
    <vxe-column title="申报金额" width="140" align="right"><template #default="{row}">{{row.currency}} {{money(row.amount)}}</template></vxe-column><vxe-column field="paymentTime" title="付款日期" width="120"/>
    <vxe-column title="凭证" width="90"><template #default="{row}"><a :href="row.voucherUrl" target="_blank" rel="noopener">查看</a></template></vxe-column>
    <vxe-column title="状态" width="100"><template #default="{row}">{{statusLabel[row.status]||row.status}}</template></vxe-column><vxe-column field="createTime" title="提交时间" width="165"/>
    <vxe-column title="操作" width="190"><template #default="{row}"><vxe-button mode="text" @click="detail(row)">详情</vxe-button><template v-if="row.status==='PENDING'"><vxe-button mode="text" status="success" @click="review(row,'approve')">通过</vxe-button><vxe-button mode="text" status="error" @click="review(row,'reject')">驳回</vxe-button></template></template></vxe-column>
  </vxe-table><vxe-pager v-model:current-page="query.pageNum" v-model:page-size="query.pageSize" :total="total" @page-change="load"/>
  <vxe-modal v-model="detailOpen" title="付款申报详情" width="650" :show-footer="false"><div v-if="current" class="detail-grid"><div>申报单号：{{current.declarationNo}}</div><div>客户：{{current.customerName}}</div><div>出货计划：{{current.shipmentNo}}</div><div>金额：{{current.currency}} {{money(current.amount)}}</div><div>状态：{{statusLabel[current.status]}}</div><div>审核人：{{current.reviewBy||'-'}}</div><div class="full">客户备注：{{current.remark||'-'}}</div><div class="full">审核意见：{{current.reviewRemark||'-'}}</div></div></vxe-modal>
  <vxe-modal v-model="reviewOpen" :title="reviewType==='approve'?'确认审核通过':'驳回付款申报'" width="520" show-footer><p v-if="reviewType==='approve'">通过后将自动生成正式收款单，并全额核销申报关联的出货计划。</p><vxe-textarea v-model="reviewRemark" :placeholder="reviewType==='reject'?'请填写驳回原因':'审核备注（可选）'" rows="4"/><template #footer><vxe-button @click="reviewOpen=false">取消</vxe-button><vxe-button :status="reviewType==='approve'?'success':'error'" :loading="saving" @click="submitReview">确认</vxe-button></template></vxe-modal>
</div></template>
<script setup name="PaymentDeclaration">
// @ts-nocheck
import{getCurrentInstance,reactive,ref}from'vue';import{listPaymentDeclaration,getPaymentDeclaration,approvePaymentDeclaration,rejectPaymentDeclaration}from'@/api/freight/paymentDeclaration';const{proxy}=getCurrentInstance();const rows=ref([]),total=ref(0),loading=ref(false),saving=ref(false),detailOpen=ref(false),reviewOpen=ref(false),current=ref(null),reviewType=ref('approve'),reviewRemark=ref('');const query=reactive({pageNum:1,pageSize:10,declarationNo:'',customerName:'',status:''});const statusLabel={PENDING:'待审核',CONFIRMED:'已通过',REJECTED:'已驳回'};const money=v=>Number(v||0).toFixed(2);function load(){loading.value=true;listPaymentDeclaration(query).then(r=>{rows.value=r.data?.rows||[];total.value=r.data?.total||0}).finally(()=>loading.value=false)}function search(){query.pageNum=1;load()}function reset(){Object.assign(query,{pageNum:1,pageSize:10,declarationNo:'',customerName:'',status:''});load()}function detail(row){getPaymentDeclaration(row.declarationId).then(r=>{current.value=r.data;detailOpen.value=true})}function review(row,type){current.value=row;reviewType.value=type;reviewRemark.value='';reviewOpen.value=true}function submitReview(){if(reviewType.value==='reject'&&!reviewRemark.value.trim()){proxy.$modal.msgWarning('请填写驳回原因');return}saving.value=true;const fn=reviewType.value==='approve'?approvePaymentDeclaration:rejectPaymentDeclaration;fn(current.value.declarationId,{remark:reviewRemark.value}).then(()=>{proxy.$modal.msgSuccess(reviewType.value==='approve'?'已生成正式收款并完成核销':'已驳回');reviewOpen.value=false;load()}).finally(()=>saving.value=false)}load()
</script><style scoped>.vxe-pager{margin-top:12px}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.full{grid-column:1/-1}</style>
